trigger:
  branches:
    include:
      - main

stages:
  - stage: "GenerateBlogContent"
    displayName: "Generating Blog Content"
    jobs:
      - job:
        pool:
          vmImage: "windows-latest"
        workspace:
          clean: all
        steps:
          - checkout: self
            displayName: "Checkout repository including submodules"
            submodules: true
        # workaround https://github.com/giuliov/hugo-vsts-extension/issues/22
          - task: PowerShell@2
            displayName: "custom Build Hugo.exe"
            inputs:
              targetType: Inline              
              pwsh: true
              script:   |
                  Write-Host "build hugo site"
                  . $(System.DefaultWorkingDirectory)/scripts/hugo.exe -b "https://blog.azurenative.nl" -s "$(System.DefaultWorkingDirectory)/src/azurenative_blog" -d "$(Pipeline.Workspace)" -F
          
       
          - publish: "$(Pipeline.Workspace)"
            artifact: "hugo-blog-content"

  - stage: "PublishHugoContent"
    variables:
      - group: "gitVault"
    displayName: "Publishing Blog Content"
    dependsOn: "GenerateBlogContent"
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - job:
        pool:
          vmImage: "windows-latest"
        steps:
          - checkout: none
          - download: current
            artifact: "hugo-blog-content"
          - task: GitHubPagesPublish@1
            displayName: "Executing GitHub Pages Publish"
            inputs:
              docPath: "$(Pipeline.Workspace)/hugo-blog-content/*"
              githubusername: "$(github-username)"
              githubemail: "$(github-email)"
              githubaccesstoken: "$(github-personal-access-token)"
              repositoryname: "$(github-repository-name)"
              branchname: "main"
              commitmessage: "CICD Pipeline $(Build.BuildNumber): $(Build.SourceVersionMessage)"
